### ISSUE TITLE
Minor typo in examples on website

### ISSUE THREAD

**Issue by deanrp2** [mradaideh/neorl#18]
In example 5, in the first code snippet:
`import neorl.benchmarks.cec17 as functions`

needs to be 
`import neorl.benchmarks.cec17 as all_functions`

I think

**Comment by mradaideh** [comment]
@deanrp2 Thank you for the note. Indeed, it is fine to call the import the way you like, it is like `import numpy as np`. Both of these calls should be fine for the user and should work. You still need to access the `all_functions` variable anyway regardless of the prefix chosen.
