### ISSUE TITLE
Stray print from neorl/benchmarks/tools/transforms.py

### ISSUE THREAD

**Issue by deanrp2** [mradaideh/neorl#19]
I am not sure what the purpose of this script but it is throwing in stray print on some imports.

**Comment by deanrp2** [comment]
print is

```
../neorl/neorl/benchmarks/tools/data.pkl
```

**Comment by mradaideh** [comment]
@deanrp2 Thank you for catching this debugging statement. This will be removed in the next version. This script applies space transformation and shift on the classical functions (e.g. Ackely, Griewank) so they become more convoluted. This data file contains the coefficients for the transformation. It is a non-py file so it needs a bit careful treatment when building the repo.
