### ISSUE TITLE
Objective function evaluation counting for ES

### ISSUE THREAD

**Issue by deanrp2** [mradaideh/neorl#3]
For Evolutionary Strategies, in the online documentation notes section, one bullet says "Total number of cost evaluations for ES is npop * ngen.".

This is incorrect, it should read "Total number of cost evaluations for ES is lambda*(ngen+1).".

**Comment by mradaideh** [comment]
Thank you @deanrp2 for catching the typo in our documentation, you are right for ES cost, all methods have been checked to ensure correct numbers are provided. This will appear in the updated documentation very soon.
