### ISSUE TITLE
Stray debug print in GWO for grid bounds 

### ISSUE THREAD

**Issue by deanrp2** [mradaideh/neorl#30]
There is a debug statement which prints even when verbose = 0 in GWO which reads: 

'--debug: grid parameter type is found in the space'

I believe this should either be removed or only included if verbose is true.

**Comment by mradaideh** [comment]
@deanrp2 Thanks for the catch. This debugging message was needed for us early on when introducing `grid` space, as we wanted to confirm certain features being activated. Given how mature this type is now, we removed this debugging message.
