### ISSUE TITLE
Parallelization results in slow-down

### ISSUE THREAD

**Issue by wcdawn** [mradaideh/neorl#42]
I have a large optimization problem I'd like to run and it should be parallelizable. I started testing with `ex2_ackerly` and increased `ncores` to any number > 1. My CPU has plenty of threads, so this shouldn't be an issue.

However, it seems like there is a huge overhead penalty when running cases in parallel. Increasing to four threads resulted in nearly 4x runtime.

Are you aware of this problem? It seems to defeat the purpose of parallelization. Could you provide an example when parallelization helps?

**Comment by mradaideh** [comment]
Hi @wcdawn. Thanks for your note. You are indeed right and we thought this might be an obvious thing. Benchmark functions (e.g., Rastrigin, Ackley) are very fast to evaluate, so Python parallel overhead is more than the cost of the function evaluation. The parallelization in NEORL is intended when the fitness function is expensive taking the order of magnitudes of seconds to hours like running a computer code in the fitness function. In the context of benchmark functions, the parallelization test will be only for verification that the capability works. Hope that addresses your concern!

**Comment by wcdawn** [comment]
Thank you @mradaideh !

I guess I was surprised by how much overhead cost was introduced by the `joblib` library. I was able to observe parallel speedup by inserting a `time.sleep(1)` into the `ACKLEY` fitness function, so it seems like the parallelization will be helpful even for even relatively fast (one second) cost functions. Just a note: the parallelization in my test was very nearly ideal so it seems like everything works well given a reasonable cost function :)
