### ISSUE TITLE
The logo ‘NEORL’ show three times when using parallelization computing (ncores > 1)

### ISSUE THREAD

**Issue by XuboGU** [mradaideh/neorl#8]
When ncores is set to more than one, then the logo 'NEORL'  will show three times rather than only once.

**Comment by mradaideh** [comment]
Thank you @XuboGU  for noticing that, I actually got this question frequently, so to clarify here we left this logo print as many as ncores to give the user a self-check that NEORL parallel engine is running fine on the algorithm end. So any failure in parallelization after seeing many logos would come from the user objective function. 

This for example may happen if you are running expensive codesin parallel as part of your objective, where you have to properly manage your code runs/files inside the objective function to avoid parallel cases crashing each other, which in this case is not a NEORL issue. Hope this clarifies the purpose.
